#!/usr/bin/env bash

if [ ! -f $HOME/.nextmsgcfg ]; then
  echo "%Y%m%d-%H%M%S" > $HOME/.nextmsgcfg
fi

FMT=$(cat $HOME/.nextmsgcfg|head -q -n 1)
if [ -z "${FMT}" ]; then
  FMT="%Y%m%d-%H%M%S"
  echo "%Y%m%d-%H%M%S" > $HOME/.nextmsgcfg
fi 

if [ "${1}" = "-z" ]; then
  echo "0" > $HOME/.nextmsg
  exit  
fi

if [ ! -f $HOME/.nextmsg ]; then
  echo "0" > $HOME/.nextmsg
fi

NEWVAL=$(($(cat $HOME/.nextmsg) + 1))
echo $NEWVAL > $HOME/.nextmsg
echo "$(date +${FMT}): Sequencenumber = ${NEWVAL}"
